name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: 
      group: gpu-group
      labels: gpu-test-runner
    container:
      image: beehivelab/tornadovm-nvidia-openjdk:1.0.6
    permissions:
      contents: read

    steps:
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle Wrapper
      run: ./gradlew -Pbabylonml.tornadovm.home=/tornado/tornado/bin/sdk build
