name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04
    container:
      image: beehivelab/tornadovm-nvidia-openjdk:1.0.6
    permissions:
      contents: read

    steps:
    # - uses: actions/setup-node@v4
    #   with:
    #     node-version: 20
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle Wrapper
      run: ./gradlew -Pbabylonml.tornadovm.home=/tornado/tornado/bin/sdk build
